version: '3'
services:
  app:
    tty: true
    image: node:8.11
    ports:
      - "${APP_PORT-5899}:${APP_PORT-5899}"
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    restart: on-failure
    entrypoint: node_modules/.bin/gulp
    environment:
      NODE_ENV: development
      PORT: ${APP_PORT-5899}
volumes:
  node_modules: {}
